#    Copyright (c) 2022 Cisco and/or its affiliates.
#    This software is licensed to you under the terms of the Cisco Sample
#    Code License, Version 1.1 (the "License"). You may obtain a copy of the
#    License at
#                   https://developer.cisco.com/docs/licenses
#    All use of the material herein must be in accordance with the terms of
#    the License. All rights not expressly granted by pytthe License are
#    reserved. Unless required by applicable law or agreed to separately in
#    writing, software distributed under the License is distributed on an "AS
#    IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
#    or implied.

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: "TCP"
      port: 6002
      targetPort: 5002

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: hakjosh/backend
          imagePullPolicy: Never
          ports:
            - containerPort: 5002
      imagePullSecrets:
        - name: secret

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: "TCP"
      port: 6001
      targetPort: 5001
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: hakjosh/frontend
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
      imagePullSecrets:
        - name: secret
