apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: microservices-basic
build:
  artifacts:
  - image: hakjosh/backend
    context: backend
    docker:
      dockerfile: Dockerfile
  - image: hakjosh/frontend
    context: frontend
    docker:
      dockerfile: Dockerfile
manifests:
  rawYaml:
  - deployment.yaml
